authapp/urls.py
from django.urls import include, path
from authapp.views import dashboard, privacy
from django.contrib.auth.decorators import login_required
# https://django-allauth.readthedocs.io/en/latest/forms.html

app_name = 'authapp'

urlpatterns = [
    path('privacy/', privacy, name='privacy'),
    path('dashboard/', dashboard, name='dashboard'),
]

howdoilearnthat/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.defaults import page_not_found

urlpatterns = [
    path('404/', page_not_found, {'exception': Exception()}),
    path('me/', include('allauth.urls')),
    path('me/', include('authapp.urls', namespace='authapp')),
    path('', include('links.urls', namespace='links')),
    path('admin/', admin.site.urls),
]

links/urls.py
from django.urls import path

from . import views

app_name = 'links'

urlpatterns = [
    path('', views.SearchList.as_view(), name='index'),
    path('suggest/', views.suggest, name='suggest'),
    path('<int:pk>/', views.LinkDetailView.as_view(), name='detail'),
    path('post/ajax/like', views.postLike, name='post_like'),
    path('post/ajax/comment', views.postComment, name='post_comment'),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    on_mailing_list = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'

links/models.py
from django.db import models
from django.conf import settings
from django.db.models import Count
from django.contrib.auth.models import User


class LinkQuerySet(models.QuerySet):
    def search(self, **kwargs):
        if len(kwargs['tags']) != 0:
            qs = self
            qs = qs.filter(approved=True)
            if kwargs.get('level', []):
                if "AN" not in kwargs['level']:
                    qs = qs.filter(level__in=[kwargs['level'], "AN"])
            if kwargs.get('type', []) and len(kwargs['type']) != 0:
                qs = qs.filter(type__in=kwargs['type'])
            if kwargs.get('tags', []):
                qs = qs.filter(tags__in=kwargs['tags'])
            qs = qs.annotate(q_count=Count('likes')).order_by('-q_count')
            return qs.distinct()
        else:
            return Link.objects.none()


class Link(models.Model):

    approved = models.BooleanField(default=False, blank=False, null=False)
    objects = LinkQuerySet.as_manager()

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='link_like', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    ADVANCED = 'AD'
    INTERMEDIATE = 'IN'
    BEGINNER = 'BE'
    ANY = "AN"
    LEVEL_CHOICES = [
        (ANY, 'Any level'),
        (BEGINNER, 'Beginner'),
        (INTERMEDIATE, 'Intermediate'),
        (ADVANCED, 'Advanced')
    ]
    level = models.CharField(
        max_length=2,
        choices=LEVEL_CHOICES,
        blank=False,
        default=ANY
    )

    PODCAST = "PO"
    YOUTUBE = "YT"
    COURSE = "CO"
    ARTICLE = "AR"
    BOOK = "BO"
    OTHER = "OT"
    TYPE_CHOICES = [
        (PODCAST, 'Podcast'),
        (YOUTUBE, 'YouTube / Video'),
        (COURSE, 'Online course (eg: Coursera)'),
        (ARTICLE, 'Article, Text or Blog'),
        (BOOK, 'Book'),
        (OTHER, 'Other')
    ]
    type = models.CharField(
        max_length=2,
        choices=TYPE_CHOICES,
        blank=False,
        default=OTHER
    )

    url = models.URLField(max_length=300, blank=False)
    description = models.TextField(max_length=500, blank=False)
    tagline = models.CharField(max_length=100, default="")
    name = models.CharField(max_length=100, blank=False)
    tags = models.ManyToManyField(
        to='links.Tag',
        related_name='links',
        blank=True
    )

    def __str__(self):
        return self.name

    def number_of_likes(self):
        return self.likes.count()


class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Comment(models.Model):
    link = models.ForeignKey(Link, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    created_on = models.DateTimeField(auto_now_add=True)
    body = models.TextField(max_length=500)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment in {} by {}'.format(self.link.name, self.user.username)

authapp/forms.py
from django.contrib.auth.models import User
from django import forms


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username",)
        labels = {
            "username": "Change your username"
        }

authapp/views.py
from django.shortcuts import render
from .forms import UserEditForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


@login_required
def dashboard(request):
    request.session['saved_back_url'] = request.get_full_path()
    liked = request.user.link_like.all()
    paginator = Paginator(liked, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        "page_obj": page_obj,
        "is_paginated": page_obj.has_next(),
        "form": user_form,
        "welcome": "Your personal space on How Should I Learn"
    }
    return render(request,"authapp/dashboard.html", context=context)


def privacy(request):
    return render(request, 'authapp/privacy.html', {})

authapp/templates/authapp/dashboard.html
{% extends "base.html" %}
{% load my_tags %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
    <h1 class="h2">{{ welcome }}</h1>
    <div class="card my-4">
        <div class="card-body">
            <p class="card-title bold-text"><i class="fas fa-user-edit"></i> Edit your account details</p>
            <form action="" method="post" class="edit-user-form">
                {% csrf_token %}
                <span class="text-danger bold-text">{{ form.username.errors }}</span>
                {{ form.username.label_tag }}
                <small class=text-muted">Your username is shown if you leave a comment</small>
                {{ form.username }}
                <button type="submit" class="btn btn-outline-info btn-sm mt-3">Save</button>
            </form>
        </div>
    </div>
    {% if page_obj %}
        <h2 class="h3">Your liked resources</h2>
        <div class="row my-4">
            {% for link in page_obj %}
                <div class="col-lg-6 mb-4">
                    <div class="card">
                        <div class="card-body d-flex flex-column">
                            <p class="card-title h6 m-0">{{ link.name }}</p>
                            <small class="card-text mb-1 ">{{ link.tagline }}</small>
                            <small class="text-danger my-1 d-block"><i class="fas fa-heart"></i> {{ link.number_of_likes }} Like{{ link.number_of_likes|pluralize }}</small>
                            <ul class="card-text">
                                {% for tag in link.tags.all %}
                                    <li>{{ tag.name }}</li>
                                {% endfor %}
                                <li>{{ link.get_level_display }}</li>
                                <li>{{ link.get_type_display }}</li>
                            </ul>
                            <div class="mt-auto flex-row-lg d-flex-lg">
                                <a href="{% url 'links:detail' link.id %}" class="btn btn-primary btn-more mt-2 me-lg-2 btn-sm me-2">More Details</a>
                                <a href="{{ link.url }}" target="_blank" class="btn btn-outline-info mt-2 btn-access btn-sm">Access Resource</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?{% param_replace page=1 %}">First</a>
                {% if page_obj.previous_page_number != 1 %}
                    <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
                {% endif %}
            {% endif %}

            Page {{ page_obj.number }} of {{ paginator.num_pages }}

            {% if page_obj.has_next %}
                {% if page_obj.next_page_number != paginator.num_pages %}
                    <a href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
                {% endif %}
                <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
            {% endif %}

            <p>Results {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
        {% endif %}
    {% else %}
        <p class="mt-2">You haven't liked any resources yet</p>
    {% endif %}

{% endblock content %}

authapp/templates/authapp/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Sign up{% endblock title %}

{% block content %}
    <div class="card text-center form-card">
        <h2 class="card-header h5">Sign up for your account</h2>
        <div class="card-body">
            <div class="col my-md-3 my-2">
                <div class="row mx-auto">
                    <a class="btn mb-2 mx-auto icon-button"
                       href="{% url 'social:begin' 'google-oauth2' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                             viewBox="0 0 48 48">
                            <defs>
                                <path id="a"
                                      d="M44.5 20H24v8.5h11.8C34.7 33.9 30.1 37 24 37c-7.2 0-13-5.8-13-13s5.8-13 13-13c3.1 0 5.9 1.1 8.1 2.9l6.4-6.4C34.6 4.1 29.6 2 24 2 11.8 2 2 11.8 2 24s9.8 22 22 22c11 0 21-8 21-22 0-1.3-.2-2.7-.5-4z"></path>
                            </defs>
                            <clipPath id="b">
                                <use xlink:href="#a" overflow="visible"></use>
                            </clipPath>
                            <path clip-path="url(#b)" fill="#FBBC05" d="M0 37V11l17 13z"></path>
                            <path clip-path="url(#b)" fill="#EA4335" d="M0 11l17 13 7-6.1L48 14V0H0z"></path>
                            <path clip-path="url(#b)" fill="#34A853" d="M0 37l30-23 7.9 1L48 0v48H0z"></path>
                            <path clip-path="url(#b)" fill="#4285F4" d="M48 48L17 24l-4-3 35-10z"></path>
                        </svg>
                        Continue with Google</a>
                </div>
                <div class="row mx-auto">
                    <a class="btn mb-2 mx-auto icon-button"
                       href="{% url 'social:begin' 'facebook' %}">
                        <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0 0V48H25.5629V29.4586H19.314V21.8895H25.5629V15.5328C25.5629 10.9097 29.3106 7.16203 33.9337 7.16203H40.4665V13.9684H35.7919C34.323 13.9684 33.132 15.1593 33.132 16.6283V21.8896H40.349L39.3516 29.4587H33.132V48H48V0H0Z"
                                  fill="#3A559F"></path>
                        </svg>
                        Continue with Facebook</a>
                </div>
            </div>
            <div class="col my-md-3 my-2">
                <p class="text-primary">Or use email</p>
                <div>
                    {% if form.errors %}
                        <p>Your username or password are invalid. Please try again.</p>
                    {% endif %}
                </div>
                <form action="" method="post" class="form login-form text-left">

                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <p style="font-size: .65em">By clicking Sign Up, you agree to our <a target="_blank"
                                                                                         href="{% url 'authapp:privacy' %}">Privacy
                        Policy</a> and that you have read our <a target="_blank" href="{% url 'authapp:privacy' %}">Privacy
                        Policy</a>.</p>
                    {% buttons %}
                        <button type="submit" class="btn btn-info">Sign up</button>
                    {% endbuttons %}
                    <p>Already have an account? <a href="{% url 'authapp:login' %}">Log in</a></p>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}