authapp/urls.py
from django.urls import include, path
from authapp.views import dashboard, privacy
from django.contrib.auth.decorators import login_required
# https://django-allauth.readthedocs.io/en/latest/forms.html

app_name = 'authapp'

urlpatterns = [
    path('privacy/', privacy, name='privacy'),
    path('dashboard/', dashboard, name='dashboard'),
]

howdoilearnthat/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.defaults import page_not_found

urlpatterns = [
    path('404/', page_not_found, {'exception': Exception()}),
    path('me/', include('allauth.urls')),
    path('me/', include('authapp.urls', namespace='authapp')),
    path('', include('links.urls', namespace='links')),
    path('admin/', admin.site.urls),
]

links/urls.py
from django.urls import path

from . import views

app_name = 'links'

urlpatterns = [
    path('', views.SearchList.as_view(), name='index'),
    path('suggest/', views.suggest, name='suggest'),
    path('<int:pk>/', views.LinkDetailView.as_view(), name='detail'),
    path('post/ajax/like', views.postLike, name='post_like'),
    path('post/ajax/comment', views.postComment, name='post_comment'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="Description"
          content="LivLearn - for lifelong learners, by lifelong learners.">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/selectize.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa+One:ital@1&display=swap" rel="stylesheet">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
          integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">


    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
<div id="page-container">
    <div id="content-wrap">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand bold-text flex-md-fill justify-content-start m-0 p-0" href="{% url 'links:index' %}">
                    <img src="{% static 'media/logo.svg' %}" alt="How Should I Learn Elephant Logo"/>
                </a>
                <span class="special-font h4 py-0 my-0 text-light text-center flex-fill justify-content-center">LIVLEARN</span>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav flex-fill justify-content-end">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item active">
                                <a href="{% url 'authapp:dashboard' %}"
                                   class="btn btn-light mx-md-2 my-1 my-md-0 d-block d-md-inline-block btn-sm"><i
                                        class="fas fa-user-alt"></i> {{ user.username }}</a>
                            </li>
                            <li class="nav-item active">
                                <a href="{% url 'account_logout' %}"
                                   class="btn-outline-light btn mx-md-2 my-1 my-md-0 d-block d-md-inline-block btn-sm"><i
                                        class="fas fa-sign-out-alt"></i>
                                    Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item active">
                                <a href="{% url 'account_signup' %}"
                                   class="btn btn-light mx-md-2 my-1 my-md-0 d-block d-md-inline-block btn-sm">Sign
                                    up</a>
                            </li>
                            <li class="nav-item active">
                                <a href="{% url 'account_login' %}"
                                   class="btn-outline-light btn mx-md-2 my-1 my-md-0 d-block d-md-inline-block btn-sm">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container" style="padding-top: 20px">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    {% include "footer.html" %}
    <!-- JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/selectize.min.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
</div>
</body>

</html>

templates/footer.html
<!-- https://mdbootstrap.com/docs/standard/navigation/footer/ -->
<footer id="footer">
    <div class="bg-light row text-center p-2 m-0">
        <div class="col-12 col-md-6 p-2 text-center text-md-start">
            <small class="footer-small">💡 Wondering "how should I learn [insert new thing here]?" - try discovering great resources on LivLearn!</small>
            <small class="footer-small">📧 Contact info@howshouldilearn.com with any enquiries</small>

        </div>
        <div class="col-12 col-md-6 p-2 text-center text-md-end">
            <small class="footer-small"><a href="{% url 'authapp:privacy' %}">View our Privacy and Cookies
                Policy</a></small>
            <small class="footer-small">© 2021 Copyright <a class="text-dark" href="https://www.howshouldilearn.com/">LivLearn - howshouldilearn.com</a></small>
            <small class="footer-small">Built with ❤️ 🐱 in London</small>
        </div>
    </div>
</footer>