howdoilearnthat/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.defaults import page_not_found

urlpatterns = [
    path('404/', page_not_found, {'exception': Exception()}),
    path('me/', include('allauth.urls')),
    path('me/', include('authapp.urls', namespace='authapp')),
    path('', include('links.urls', namespace='links')),
    path('admin/', admin.site.urls),
]

links/urls.py
from django.urls import path

from . import views

app_name = 'links'

urlpatterns = [
    path('', views.SearchList.as_view(), name='index'),
    path('suggest/', views.suggest, name='suggest'),
    path('<int:pk>/', views.LinkDetailView.as_view(), name='detail'),
    path('post/ajax/like', views.postLike, name='post_like'),
    path('post/ajax/comment', views.postComment, name='post_comment'),
]

links/models.py
from django.db import models
from django.conf import settings
from django.db.models import Count
from django.contrib.auth.models import User


class LinkQuerySet(models.QuerySet):
    def search(self, **kwargs):
        if len(kwargs['tags']) != 0:
            qs = self
            qs = qs.filter(approved=True)
            if kwargs.get('level', []):
                if "AN" not in kwargs['level']:
                    qs = qs.filter(level__in=[kwargs['level'], "AN"])
            if kwargs.get('type', []) and len(kwargs['type']) != 0:
                qs = qs.filter(type__in=kwargs['type'])
            if kwargs.get('tags', []):
                qs = qs.filter(tags__in=kwargs['tags'])
            qs = qs.annotate(q_count=Count('likes')).order_by('-q_count')
            return qs.distinct()
        else:
            return Link.objects.none()


class Link(models.Model):

    approved = models.BooleanField(default=False, blank=False, null=False)
    objects = LinkQuerySet.as_manager()

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='link_like', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    ADVANCED = 'AD'
    INTERMEDIATE = 'IN'
    BEGINNER = 'BE'
    ANY = "AN"
    LEVEL_CHOICES = [
        (ANY, 'Any level'),
        (BEGINNER, 'Beginner'),
        (INTERMEDIATE, 'Intermediate'),
        (ADVANCED, 'Advanced')
    ]
    level = models.CharField(
        max_length=2,
        choices=LEVEL_CHOICES,
        blank=False,
        default=ANY
    )

    PODCAST = "PO"
    YOUTUBE = "YT"
    COURSE = "CO"
    ARTICLE = "AR"
    BOOK = "BO"
    OTHER = "OT"
    TYPE_CHOICES = [
        (PODCAST, 'Podcast'),
        (YOUTUBE, 'YouTube / Video'),
        (COURSE, 'Online course (eg: Coursera)'),
        (ARTICLE, 'Article, Text or Blog'),
        (BOOK, 'Book'),
        (OTHER, 'Other')
    ]
    type = models.CharField(
        max_length=2,
        choices=TYPE_CHOICES,
        blank=False,
        default=OTHER
    )

    url = models.URLField(max_length=300, blank=False)
    description = models.TextField(max_length=500, blank=False)
    tagline = models.CharField(max_length=100, default="")
    name = models.CharField(max_length=100, blank=False)
    tags = models.ManyToManyField(
        to='links.Tag',
        related_name='links',
        blank=True
    )

    def __str__(self):
        return self.name

    def number_of_likes(self):
        return self.likes.count()


class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Comment(models.Model):
    link = models.ForeignKey(Link, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    created_on = models.DateTimeField(auto_now_add=True)
    body = models.TextField(max_length=500)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment in {} by {}'.format(self.link.name, self.user.username)

links/forms.py
from django import forms
from .models import Tag, Link


class SearchForm(forms.Form):
    type = forms.MultipleChoiceField(label='Filter by resource type', choices=Link.TYPE_CHOICES, required=False, widget=forms.CheckboxSelectMultiple)
    tags = forms.ModelMultipleChoiceField(label='What do you want to learn?', queryset=Tag.objects.all(), required=False)
    level = forms.ChoiceField(label='Experience level', choices=Link.LEVEL_CHOICES, required=False)

    def clean(self):
        cleaned_data = super().clean()
        level = cleaned_data.get("level")
        type = cleaned_data.get("type")
        tags = cleaned_data.get("tags")
        if len(level) == 0 and len(type) == 0 and len(tags) == 0:
            raise forms.ValidationError("No search or filter parameters specified")


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ["name",  "url", "type", "tagline", "description", "level"]

links/views.py
from django.shortcuts import get_object_or_404, render
from .models import Link, Tag, Comment
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.detail import DetailView
from .forms import SearchForm, LinkForm
from django.views.generic import ListView
from django.http import JsonResponse


class SearchList(ListView):
    model = Link
    template_name = "links/index.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = SearchForm(self.request.GET)
        self.request.session['saved_back_url'] = self.request.get_full_path()
        if form.is_valid():
            return queryset.search(**form.cleaned_data)

        else:
            return queryset.filter(approved=True).order_by('-created_at')[:5]

    def get_context_data(self, **kwargs):
        searched = False
        list_title = "Recently posted links"
        form = SearchForm(self.request.GET)
        if form.is_valid():
            searched = True
            list_title = "Search results"
        context = super(SearchList, self).get_context_data(**kwargs)
        context['list_title'] = list_title
        context['searched'] = searched
        context['all_tags'] = [tag.name for tag in Tag.objects.all()]
        context['form'] = form
        return context


class LinkDetailView(DetailView):

    model = Link

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        likes_connected = get_object_or_404(Link, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True
        saved_back_url = self.request.session.get("saved_back_url")
        if saved_back_url:
            data["saved_back_url"] = saved_back_url
        else:
            data["saved_back_url"] = reverse('links:index')
        data['number_of_likes'] = likes_connected.number_of_likes()
        data['post_is_liked'] = liked
        return data


def postLike(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        # get the form data
        link = Link.objects.get(id=request.POST.get('link_id'))
        if link:
            if link.likes.filter(id=request.user.id).exists():
                link.likes.remove(request.user)
                return JsonResponse({"post_is_liked": False, "num_likes": link.likes.count()}, status=200)
            else:
                link.likes.add(request.user)
                return JsonResponse({"post_is_liked": True, "num_likes": link.likes.count()}, status=200)


def postComment(request):
    if request.is_ajax and request.method == "POST":
        if request.user.is_authenticated:
            body = request.POST.get('body')
            link = Link.objects.get(id=request.POST.get('link_id'))
            if link:
                comment = Comment(user=request.user, link=link, body=body)
                comment.save()
                return JsonResponse({"posted_body": str(body), "username": str(request.user.username), "num_comments": link.comments.all().count()}, status=200)
        else:
            return HttpResponseRedirect(reverse('authapp:login'))



def suggest(request):
    if request.method == 'POST':
        form = LinkForm(request.POST or None)
        if form.is_valid():
            new_link = form.save(commit=False)
            new_link.approved = False
            new_link.save()
            return HttpResponseRedirect(reverse('links:index'))
    else:
        form = LinkForm()

    context = {
        "form": form
    }

    saved_back_url = request.session.get("saved_back_url")
    if saved_back_url:
        context["saved_back_url"] = saved_back_url
    else:
        context["saved_back_url"] = reverse('links:index')

    return render(request, 'links/suggest.html', context=context)

links/templates/links/index.html
{% extends "base.html" %}
{% load my_tags %}
{% block title %}LivLearn{% endblock title %}
{% block content %}
    {% if searched %}
        <p id="searched" class="d-none"></p>
    {% endif %}
    <h1 class="h5 mb-3">A carefully curated directory of original, fun and diverse tech-related learning resources.</h1>
    <form class="w-100 mx-auto" action="" method="get">
        <div class="tags_wrapper my-2 w-100 mx-auto">
            {{ form.tags.errors }}
            <span class="tags_input">{{ form.tags }}</span>
        </div>
        <div class="resource_type_wrapper my-2 w-100 mx-auto">
            {{ form.type.errors }}
            <span class="bold-text d-block">{{ form.type.label_tag }}</span>
            {{ form.type }}
        </div>
        <div class="experience_level_wrapper my-2 w-100 mx-auto">
            {{ form.level.errors }}
            <span class="bold-text">{{ form.level.label_tag }}</span>
            {{ form.level }}
        </div>
        <div class="mt-3 mx-auto w-75">
            <button type="submit" class="btn btn-primary btn-block mx-auto w-100"><i class="fas fa-search"></i> Find Resources!</button>
            <a href="{% url 'links:suggest' %}" class="btn btn-outline-info w-100 mt-2 btn-block mx-auto"><i class="fas fa-plus"></i>
                Share Resource</a>
        </div>
    </form>
    {% if page_obj %}
        <h2 class="mt-4" id="results">{{ list_title }}</h2>
        <div class="row my-4">
            {% for link in page_obj %}
                <div class="col-lg-6 mb-4">
                    <div class="card">
                        <div class="card-body d-flex flex-column">
                            <p class="card-title h6 m-0">{{ link.name }}</p>
                            <small class="card-text mb-1">{{ link.tagline }}</small>
                            <small class="text-danger my-1 d-block"><i
                                    class="fas fa-heart"></i> {{ link.number_of_likes }}
                                Like{{ link.number_of_likes|pluralize }}</small>
                            <ul class="card-text">
                                {% for tag in link.tags.all %}
                                    <li>{{ tag.name }}</li>
                                {% endfor %}
                                <li>{{ link.get_level_display }}</li>
                                <li>{{ link.get_type_display }}</li>
                            </ul>
                            <div class="mt-auto flex-row-lg d-flex-lg">
                                <a href="{% url 'links:detail' link.id %}"
                                   class="btn btn-primary btn-more mt-2 me-lg-2 btn-sm me-2">More Details</a>
                                <a href="{{ link.url }}" target="_blank"
                                   class="btn btn-outline-info mt-2 btn-access btn-sm">Access Resource</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?{% param_replace page=1 %}">First</a>
                {% if page_obj.previous_page_number != 1 %}
                    <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
                {% endif %}
            {% endif %}

            Page {{ page_obj.number }} of {{ paginator.num_pages }}

            {% if page_obj.has_next %}
                {% if page_obj.next_page_number != paginator.num_pages %}
                    <a href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
                {% endif %}
                <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
            {% endif %}

            <p>Results {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
        {% endif %}
    {% else %}
        <div id="none-text">
            <p class="mt-4 bold-text">😿 No links found</p>
            <p>Let us know what topic you'd like us to curate more resources on - get in touch at info@howshouldilearn.com</p>
        </div>
        <p><a href="{% url 'links:index' %}"><i class="far fa-hand-point-left"></i> Back to home</a></p>
    {% endif %}
{% endblock content %}

{% block javascript %}
    <script>
        $('#id_tags').selectize({
            openOnFocus: false,
            closeAfterSelect: true,
            placeholder: "Search for learning resource topics..."
        });
        if (document.getElementById("searched")) {
            const searchResults = document.getElementById("results");
            if (searchResults) {
                searchResults.scrollIntoView();
            }
        }
        const noResultsSection = document.getElementById("none-text");
        const selectedItemsCount = document.getElementsByClassName("item").length;
        if ((selectedItemsCount === 0) && noResultsSection) {
            noResultsSection.innerHTML = "<p class='mt-4 text-warning'><i class='fas fa-exclamation-circle'></i> You haven't selected any topics - please try selecting some topics</p>"
        }
        const options = Array.prototype.filter.call(document.getElementsByTagName("input"), (i) => {return (i.name === "type")});
        if (Array.prototype.filter.call(options, (i) => {return i.checked;}).length === 0) {
            Array.prototype.forEach.call(options, (o) => {o.click()})
        }
    </script>
{% endblock javascript %}

links/templates/links/link_detail.html
{% extends "base.html" %}
{% block title %}{{ object.name }}{% endblock title %}
{% block content %}
    <div class="card text-center info-card">
        <h1 class="card-header h4 py-3">{{ object.name }}</h1>
        <div class="card-body">
            <div>
                {% if user.is_authenticated %}
                    <form id="like-form">
                        {% csrf_token %}
                        <input name="link_id" value="{{ object.id }}" type="hidden">
                        {% if post_is_liked %}
                            <button class="text-danger unstyled-button" id="num-likes" type="submit"><i class="fas fa-heart"></i> {{ object.number_of_likes }} Like{{ object.number_of_likes|pluralize }}</button>
                        {% else %}
                            <button class="text-danger unstyled-button" id="num-likes" type="submit"><i class="far fa-heart"></i> {{ object.number_of_likes }} Like{{ object.number_of_likes|pluralize }}</button>
                        {% endif %}
                    </form>
                {% else %}
                    <p class="text-danger" id="num-likes"><i class="fas fa-heart"></i> {{ object.number_of_likes }} Like{{ object.number_of_likes|pluralize }}</p>
                    <a class="btn btn-outline-info btn-sm" href="{% url 'account_login' %}?next={{ request.path }}">Login to like this resource!</a><br>
                {% endif %}
            </div>
            <p class="card-text mt-3 ">{{ object.description }}</p>
            <ul class="mt-3 card-text">
                {% for tag in link.tags.all %}
                    <li>{{ tag.name }}</li>
                {% endfor %}
            </ul>
            <p class="card-text h6 mt-3">Level:</p>
            <p class="card-text">{{ object.get_level_display }}</p>
            <p class="card-text h6">Category:</p>
            <p class="card-text">{{ object.get_type_display }}</p>
            <a href="{{ object.url }}" target="_blank" class="btn btn-primary d-block d-sm-inline-block">Check out resource</a>
        </div>
        <div class="card-footer text-muted">Posted on {{ object.created_at|date:"D d M Y" }}</div>
    </div>
    <p class="info-card mt-2"><a href="{{ saved_back_url }}"><i class="far fa-hand-point-left"></i> Back</a></p>



    <div class="p-3" id="leave-a-comment">
        {% if user.is_authenticated %}
            <form id="comment-form">
                {% csrf_token %}
                <input name="link_id" value="{{ object.id }}" type="hidden">
                <div class="form-outline mb-4">
                    <textarea class="form-control" id="body" rows="4" name="body"></textarea>
                    <label class="form-label" for="body">Leave a comment...</label>
                </div>
                <button type="submit" class="btn btn-outline-primary btn-sm">Post Comment</button>
            </form>
        {% else %}
            <a href="{% url 'account_login' %}?next={{ request.path }}" class="text-decoration-underline">Login to leave
                a comment</a><br>
        {% endif %}
    </div>




    {% if object.comments.all.count > 0 %}
        <h1 class="h3 text-center mt-3" id="num-comments"><i class="fas fa-comments"></i> {{ object.comments.all.count }}
            Comment{{ object.comments.all.count|pluralize }}</h1>
        <div class="p-3" id="comment-section">
            {% for comment in object.comments.all %}
                <div class="mb-3">
                    <small><b><span class="text-muted"><i class="far fa-comment-dots"></i> {{ comment.user.username }}</span> posted
                        on {{ comment.created_on|date:"d M Y" }}</b></small>
                    <p>{{ comment.body }}</p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="h3 text-center mt-3" id="num-comments"><i class="fas fa-comment-slash"></i> No comments yet</h1>
        <div class="p-3" id="comment-section">
        </div>
    {% endif %}

{% endblock content %}



{% block javascript %}
    <script>

        $("#like-form").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            const serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'links:post_like' %}",
                data: serializedData,
                success: function (response) {
                    const post_is_liked = JSON.parse(response["post_is_liked"]);
                    const num_likes = JSON.parse(response["num_likes"]);
                    if (post_is_liked) {
                        $("#num-likes").html('<i class="fas fa-heart"></i> ' + num_likes + ((num_likes > 1) ? ' Likes' : ' Like'));
                    } else {
                        $("#num-likes").html('<i class="far fa-heart"></i> ' + num_likes + ((num_likes > 1) ? ' Likes' : ' Like'));
                    }
                },
                error: function (response) {
                    console.log("Error liking link");
                }
            })
        });

        $("#comment-form").submit(function (e) {
            e.preventDefault();
            const serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url: "{% url 'links:post_comment' %}",
                data: serializedData,
                success: function (response) {
                    const poster_username = response["username"];
                    const body = response["posted_body"];
                    const num_comments = response["num_comments"];
                    $("#comment-section").prepend('<div class="mb-3"><small><b><span class="text-muted"><i class="far fa-comment-dots"></i> ' + poster_username + '</span> posted Just Now</b></small> <p>' + body + '</p></div>')
                    $("#comment-form")[0].reset();
                    $("#num-comments").html('<i class="fas fa-comments"></i> '+num_comments + ((num_comments > 1) ? ' Comments' : ' Comment'));
                },
                error: function (response) {
                    console.log("Error posting comment");
                }
            })
        });
    </script>
{% endblock javascript %}

links/templates/links/suggest.html
{% extends "base.html" %}
{% block title %}Suggest A Resource{% endblock title %}
{% block content %}
    <div class="card">
        <div class="card-header h5 py-3">💡 Share a great learning resource that helped you</div>
        <div class="card-body">
            <form action="" method="POST" class="form suggest-form">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.name.errors }}
                    {{ form.name.label_tag }}
                    <small class="text-muted">What is the name of the resource? (Try to use the official course / article / video etc. name)</small>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    {{ form.url.errors }}
                    {{ form.url.label_tag }}
                    <small class="text-muted">Paste in a link to the resource or a relevant webpage.</small>
                    {{ form.url }}
                </div>
                <div class="form-group">
                    {{ form.type.errors }}
                    {{ form.type.label_tag }}
                    <small class="text-muted">Please choose a suitable resource type.</small>
                    {{ form.type }}
                </div>
                <div class="form-group">
                    {{ form.tagline.errors }}
                    {{ form.tagline.label_tag }}
                    <small class="text-muted">A short tagline that describes this resource as concisely as possible.</small>
                    {{ form.tagline }}
                </div>
                <div class="form-group">
                    {{ form.description.errors }}
                    {{ form.description.label_tag }}
                    <small class="text-muted">Keep it short and sweet. Why is the resource useful? Who is it for?</small>
                    {{ form.description }}
                </div>
                <div class="form-group">
                    {{ form.level.errors }}
                    {{ form.level.label_tag }}
                    <small class="text-muted">What level of learner is this resource for?</small>
                    {{ form.level }}
                </div>
                <button type="submit" class="mt-3 btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="card-footer text-muted">
            <small>🙏 Thank you for sharing your recommendation with the community!</small>
        </div>
    </div>

    <p class="m-2"><a href="{{ saved_back_url }}"><i class="far fa-hand-point-left"></i> Back</a></p>

{% endblock content %}